### PR TITLE
Bump and crd cleanup

### PR DESCRIPTION
**Pull request by jboyd01**
mirrors https://github.com/openshift/cluster-openshift-apiserver-operator/pull/173  to give crd validation schema for ServiceCatalogAPIServer

### CODE REVIEW

**Comment by jboyd01** [comment]
```
2019/03/28 17:49:28 Build src succeeded after 2m17s
2019/03/28 17:49:28 Building cluster-svcat-apiserver-operator
2019/03/28 17:50:29 Build cluster-svcat-apiserver-operator succeeded after 1m0s
2019/03/28 17:50:29 Tagging cluster-svcat-apiserver-operator into stable
2019/03/28 17:50:30 Create release image registry.svc.ci.openshift.org/ci-op-0b1rthfj/release:latest
2019/03/28 17:51:05 error: unable to signal to artifacts container to terminate in pod release-latest, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")
2019/03/28 17:51:05 error: unable to retrieve artifacts from pod release-latest: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
```
/retest

**Comment by jboyd01** [comment]
another new e2e failure:
```
019/03/28 18:38:53 Create release image registry.svc.ci.openshift.org/ci-op-7nzmj56r/release:latest
info: Using registry public hostname registry.svc.ci.openshift.org
info: Found 124 images in image stream
info: Manifests will be extracted to /tmp/release-image-0.0.1-2019-03-28-183857826257161
Loading manifests from cluster-storage-operator: sha256:5cc5028da7216d94ff280158cfce3006eef3d014d2651c785e2ec31e99f63028 ...
Loading manifests from cluster-kube-apiserver-operator: sha256:7201ae707e5345237aee6dfbdbde5f8cc6de4350bcee5b07e4d5d2996e566c6b ...
..........
Loading manifests from service-ca-operator: sha256:9389691a64ac2c3cb8a9ccdc611bafd43e57072fb8845a8874583c443d6dc1de ...
info: Included 80 referenced images into the payload
Uploading ... 38.72kB/s
error: unable to upload the new image manifest: received unexpected HTTP status: 504 Gateway Time-out
2019/03/28 18:42:37 Container release in pod release-latest failed, exit code 1, reason Error
2019/03/28 18:42:53 Ran for 6m50s
error: could not run steps: release "release-latest" failed: the pod ci-op-7nzmj56r/release-latest failed after 3m54s (failed containers: release): ContainerFailed one or more containers exited
```
/retest

**Review by jmrodri — APPROVED** [review]
LGTM

**Pull request merged**
