### PR TITLE
operator pull policy should be IfNotPresent, don't clobber operand's policy

### PR DESCRIPTION
**Pull request by jboyd01**
also update the default log level to 3 to match what we used in 3.11

### CODE REVIEW

**Comment by jwforres** [comment]
@jboyd01 aren't you making the same change in your other PR https://github.com/openshift/cluster-svcat-apiserver-operator/pull/36/files#diff-5732af35dd481279f78d8ffa3027099bL23

**Comment by jboyd01** [comment]
> @jboyd01 aren't you making the same change in your other PR https://github.com/openshift/cluster-svcat-apiserver-operator/pull/36/files#diff-5732af35dd481279f78d8ffa3027099bL23

Yes, I did include the change for PullPolicy in deployment.yaml in both PRs.  The other changes are not dups.

**Review by jmrodri — APPROVED** [review]
Looks simple enough. +1

**Pull request merged**
