### PR TITLE
Bug 1831019: Upgradeable = False, link to OpenShift docs

### PR DESCRIPTION
**Pull request by jmrodri**
The service catalog is deprecated. In OpenShift 4.4, we will block
upgrades to 4.5 or later by setting the Upgradeable field to False.
This PR updates the message to point to the documentation that states
that.

### CODE REVIEW

**Comment by shawn-hurley** [comment]
Setting valid bug override because 4.5 does not contain service catalog

**Review by joelanford — APPROVED** [review]
/lgtm

**Comment by ashcrow** [comment]
I spoke with @jmrodri and he noted the code changed here is no longer in master (hence why this isn't a backport).

**Pull request merged**
