### PR TITLE
Bug 1875900: verify the e2e test removed

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As title, modify the README to verify if the e2e test removed from the master branch. Details: https://bugzilla.redhat.com/show_bug.cgi?id=1875900

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
@jmrodri Could you help review and merge it? Thanks! It did fix a doc link.

**Comment by jianzhangbjz** [comment]
/retitle Bug 1875900: verify the e2e test removed

**Review by jmrodri — APPROVED** [review]
/lgtm
/approve

**Pull request closed without merging**
