### PR TITLE
fix logging the operator name

### LINKED ISSUE #3: fix logging messages
says openshiftapiserveroperator:
https://github.com/openshift/cluster-svcat-apiserver-operator/blob/master/pkg/operator/workloadcontroller/workload_controller.go#L155

### PR DESCRIPTION
**Pull request by jboyd01**
fixes #3

### CODE REVIEW

**Comment by bparees** [comment]
i think @jwforres said she was gonna setup CI for you on this repo, let's make sure we have that before stuff starts merging

**Comment by jboyd01** [comment]
Thanks for the help @bparees

**Pull request merged**
