### PR TITLE
Re-add service catalog apiserver removal job

### PR DESCRIPTION
**Pull request by jmrodri**
Revert "Revert "Add service catalog apiserver removal job""

This reverts commit 25d653b7e68f3a02b386e552e26864a27a421e2a.

Original PR:
https://github.com/openshift/cluster-svcat-apiserver-operator/pull/74

### CODE REVIEW

**Comment by jmrodri** [comment]
To see the commits from the original PR see https://github.com/openshift/cluster-svcat-apiserver-operator/pull/74/commits

**Comment by wking** [comment]
[upgrade][1]:

```
fail [github.com/openshift/origin/test/extended/util/disruption/disruption.go:236]: Mar 25 04:00:30.910: Service was unreachable during disruption for at least 4m54s of 34m5s (14%):
```

which is an unrelated flake.

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-svcat-apiserver-operator/80/pull-ci-openshift-cluster-svcat-apiserver-operator-master-e2e-aws-upgrade/1

**Comment by wking** [comment]
[upgrade][1] has a strange divergence between the ProwJob:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-svcat-apiserver-operator/80/pull-ci-openshift-cluster-svcat-apiserver-operator-master-e2e-aws-upgrade/2/prowjob.json | jq -r .status.state
failure
```

and the summary:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-svcat-apiserver-operator/80/pull-ci-openshift-cluster-svcat-apiserver-operator-master-e2e-aws-upgrade/2/finished.json | jq -r .result
SUCCESS
```

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-svcat-apiserver-operator/80/pull-ci-openshift-cluster-svcat-apiserver-operator-master-e2e-aws-upgrade/2

**Comment by shawn-hurley** [comment]
/lgtm

Passing upgrade tests from 4.4.0-rc.4 via manual test as well as multiple runs of the upgrade job.

**Comment by hexfusion** [comment]
@shawn-hurley I think we are seeing this fail[1]

> s: "Cluster did not complete upgrade: timed out waiting for the condition: Could not update job \"openshift-service-catalog-removed/openshift-service-catalog-apiserver-remover\" (492 of 565): the object is invalid, possibly due to local cluster configuration",

[1] https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/289/pull-ci-openshift-cluster-etcd-operator-master-e2e-gcp-upgrade/1254

**Comment by smarterclayton** [comment]
It looks like this fails if the installed version didn’t have the code change.

You probably have to test using the bot to successfully merge this.

In the meantime I’m reverting.

**Comment by jmrodri** [comment]
@smarterclayton I've tested with cluster-bot and the upgrades passed twice.

**Pull request merged**
